-- ================================================================
-- BatataCore 2.0 - Estrutura, autenticação, RLS e funções do sistema
-- Execute este arquivo no SQL Editor do projeto Supabase.
-- Faça backup antes de aplicar em um projeto com dados importantes.
-- ================================================================

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

-- ----------------------------------------------------------------
-- Tabelas principais
-- ----------------------------------------------------------------

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null default '',
    email text not null default '',
    phone text,
    city text,
    role text not null default 'participante',
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint profiles_role_check check (role in ('admin','organizador','equipe','participante'))
);

create table if not exists public.eventos (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    owner_id uuid references auth.users(id) on delete set null,
    nome text not null,
    slug text not null unique,
    categoria text not null default 'Evento',
    data_evento date not null,
    hora_inicio time,
    hora_fim time,
    local text not null,
    endereco text,
    formato text not null default 'Presencial',
    vagas_total integer not null default 1,
    vagas_ocupadas integer not null default 0,
    descricao text not null default '',
    imagem_url text,
    status text not null default 'rascunho',
    destaque boolean not null default false,
    certificado_disponivel boolean not null default false,
    carga_horaria numeric(6,2),
    deleted_at timestamptz,
    constraint eventos_vagas_check check (vagas_total > 0 and vagas_ocupadas >= 0 and vagas_ocupadas <= vagas_total),
    constraint eventos_status_check check (status in ('rascunho','publicado','cancelado','encerrado','arquivado')),
    constraint eventos_formato_check check (formato in ('Presencial','Online','Híbrido'))
);

create table if not exists public.inscritos (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    user_id uuid references auth.users(id) on delete set null,
    evento_id bigint references public.eventos(id) on delete restrict,
    nome text not null,
    email text not null,
    telefone text not null,
    cidade text not null,
    evento text not null,
    tipo text not null,
    observacao text not null default '',
    status text not null default 'confirmado',
    ticket_code text not null default encode(gen_random_bytes(12), 'hex'),
    checked_in_at timestamptz,
    cancelled_at timestamptz,
    consentimento_lgpd boolean not null default false,
    constraint inscritos_status_check check (status in ('confirmado','lista_espera','cancelado','pendente')),
    constraint inscritos_ticket_unique unique (ticket_code)
);

create table if not exists public.contatos (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    user_id uuid references auth.users(id) on delete set null,
    nome text not null,
    email text not null,
    assunto text not null,
    mensagem text not null,
    status text not null default 'aberto',
    resposta text,
    responded_at timestamptz,
    constraint contatos_status_check check (status in ('aberto','em_atendimento','resolvido','arquivado'))
);

create table if not exists public.certificados (
    id bigint generated by default as identity primary key,
    inscricao_id bigint not null unique references public.inscritos(id) on delete cascade,
    codigo uuid not null unique default gen_random_uuid(),
    emitted_at timestamptz not null default now()
);

create table if not exists public.email_queue (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    processed_at timestamptz,
    recipient text not null,
    template text not null,
    payload jsonb not null default '{}'::jsonb,
    status text not null default 'pendente',
    attempts integer not null default 0,
    last_error text,
    constraint email_queue_status_check check (status in ('pendente','processando','enviado','erro'))
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    actor_id uuid references auth.users(id) on delete set null,
    action text not null,
    entity text not null,
    entity_id text,
    details jsonb not null default '{}'::jsonb
);

-- ----------------------------------------------------------------
-- Compatibilidade com tabelas antigas já existentes
-- ----------------------------------------------------------------

alter table public.eventos add column if not exists updated_at timestamptz not null default now();
alter table public.eventos add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table public.eventos add column if not exists hora_inicio time;
alter table public.eventos add column if not exists hora_fim time;
alter table public.eventos add column if not exists endereco text;
alter table public.eventos add column if not exists imagem_url text;
alter table public.eventos add column if not exists destaque boolean not null default false;
alter table public.eventos add column if not exists certificado_disponivel boolean not null default false;
alter table public.eventos add column if not exists carga_horaria numeric(6,2);
alter table public.eventos add column if not exists deleted_at timestamptz;

alter table public.inscritos add column if not exists updated_at timestamptz not null default now();
alter table public.inscritos add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.inscritos add column if not exists evento_id bigint references public.eventos(id) on delete restrict;
alter table public.inscritos add column if not exists status text not null default 'confirmado';
alter table public.inscritos add column if not exists ticket_code text default encode(gen_random_bytes(12), 'hex');
alter table public.inscritos add column if not exists checked_in_at timestamptz;
alter table public.inscritos add column if not exists cancelled_at timestamptz;
alter table public.inscritos add column if not exists consentimento_lgpd boolean not null default false;
update public.inscritos set ticket_code = encode(gen_random_bytes(12), 'hex') where ticket_code is null or ticket_code = '';
alter table public.inscritos alter column ticket_code set not null;

alter table public.contatos add column if not exists updated_at timestamptz not null default now();
alter table public.contatos add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.contatos add column if not exists resposta text;
alter table public.contatos add column if not exists responded_at timestamptz;

-- Índices para consultas frequentes
create index if not exists idx_eventos_status_data on public.eventos(status, data_evento);
create index if not exists idx_eventos_owner on public.eventos(owner_id);
create index if not exists idx_inscritos_evento on public.inscritos(evento_id);
create index if not exists idx_inscritos_user on public.inscritos(user_id);
create index if not exists idx_inscritos_email on public.inscritos(lower(email));
create index if not exists idx_inscritos_ticket on public.inscritos(ticket_code);
create index if not exists idx_contatos_status on public.contatos(status, created_at desc);
create index if not exists idx_email_queue_status on public.email_queue(status, created_at);
do $$
begin
    create unique index uq_inscricao_ativa_email_evento
        on public.inscritos(lower(email), evento_id)
        where evento_id is not null and status <> 'cancelado';
exception
    when duplicate_table then null;
    when unique_violation then
        raise notice 'Existem inscrições duplicadas; o índice único não foi criado. Revise os dados e execute novamente.';
end $$;
create unique index if not exists uq_inscritos_ticket_code on public.inscritos(ticket_code);

-- ----------------------------------------------------------------
-- Funções auxiliares e gatilhos
-- ----------------------------------------------------------------

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select exists (
        select 1
        from public.profiles p
        where p.id = (select auth.uid())
          and p.role in ('admin','organizador')
    );
$$;
revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    insert into public.profiles(id, full_name, email, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.email, ''),
        'participante'
    )
    on conflict (id) do update
       set email = excluded.email,
           full_name = case when public.profiles.full_name = '' then excluded.full_name else public.profiles.full_name end;
    return new;
end;
$$;

create or replace function private.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if old.role is distinct from new.role
       and (select auth.uid()) is not null
       and not private.is_admin() then
        raise exception 'Apenas administradores podem alterar níveis de acesso.';
    end if;
    return new;
end;
$$;

create or replace function private.log_admin_action()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_action text;
    v_id text;
begin
    if tg_op = 'INSERT' then
        v_action := 'insert';
        v_id := new.id::text;
    elsif tg_op = 'UPDATE' then
        v_action := 'update';
        v_id := new.id::text;
    else
        v_action := 'delete';
        v_id := old.id::text;
    end if;

    if (select auth.uid()) is not null then
        insert into public.audit_logs(actor_id, action, entity, entity_id)
        values ((select auth.uid()), v_action, tg_table_name, v_id);
    end if;

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

-- Triggers idempotentes
-- Garante perfis para usuários criados antes desta migração.
insert into public.profiles(id, full_name, email, role)
select u.id, coalesce(u.raw_user_meta_data ->> 'full_name', ''), coalesce(u.email, ''), 'participante'
from auth.users u
on conflict (id) do nothing;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert or update of email on auth.users
    for each row execute function private.handle_new_user();

drop trigger if exists protect_profile_role_trigger on public.profiles;
create trigger protect_profile_role_trigger
    before update on public.profiles
    for each row execute function private.protect_profile_role();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
    for each row execute function private.touch_updated_at();

drop trigger if exists eventos_touch_updated_at on public.eventos;
create trigger eventos_touch_updated_at before update on public.eventos
    for each row execute function private.touch_updated_at();

drop trigger if exists inscritos_touch_updated_at on public.inscritos;
create trigger inscritos_touch_updated_at before update on public.inscritos
    for each row execute function private.touch_updated_at();

drop trigger if exists contatos_touch_updated_at on public.contatos;
create trigger contatos_touch_updated_at before update on public.contatos
    for each row execute function private.touch_updated_at();

drop trigger if exists eventos_audit_trigger on public.eventos;
create trigger eventos_audit_trigger after insert or update or delete on public.eventos
    for each row execute function private.log_admin_action();

drop trigger if exists inscritos_audit_trigger on public.inscritos;
create trigger inscritos_audit_trigger after update or delete on public.inscritos
    for each row execute function private.log_admin_action();

-- ----------------------------------------------------------------
-- RPC pública segura: inscrição com controle atômico de vagas
-- ----------------------------------------------------------------

create or replace function public.criar_inscricao(
    p_evento_id bigint,
    p_nome text,
    p_email text,
    p_telefone text,
    p_cidade text,
    p_tipo text,
    p_observacao text default '',
    p_consentimento_lgpd boolean default false
)
returns table(id bigint, ticket_code text, status text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_evento public.eventos%rowtype;
    v_status text;
    v_id bigint;
    v_ticket text;
begin
    if not p_consentimento_lgpd then
        raise exception 'É necessário aceitar o tratamento de dados para concluir a inscrição.';
    end if;

    if length(trim(coalesce(p_nome, ''))) < 3
       or position('@' in coalesce(p_email, '')) < 2
       or length(regexp_replace(coalesce(p_telefone, ''), '\D', '', 'g')) < 10 then
        raise exception 'Dados de inscrição inválidos.';
    end if;

    select * into v_evento
    from public.eventos
    where eventos.id = p_evento_id
      and eventos.deleted_at is null
    for update;

    if not found then
        raise exception 'Evento não encontrado.';
    end if;

    if v_evento.status <> 'publicado' then
        raise exception 'Este evento não está aberto para inscrições.';
    end if;

    if v_evento.data_evento < current_date then
        raise exception 'Este evento já foi encerrado.';
    end if;

    if exists (
        select 1 from public.inscritos i
        where i.evento_id = p_evento_id
          and lower(i.email) = lower(trim(p_email))
          and i.status <> 'cancelado'
    ) then
        raise exception 'Já existe uma inscrição ativa para este e-mail neste evento.';
    end if;

    v_status := case
        when v_evento.vagas_ocupadas >= v_evento.vagas_total then 'lista_espera'
        else 'confirmado'
    end;

    insert into public.inscritos(
        user_id, evento_id, nome, email, telefone, cidade,
        evento, tipo, observacao, status, consentimento_lgpd
    ) values (
        (select auth.uid()), p_evento_id, trim(p_nome), lower(trim(p_email)),
        trim(p_telefone), trim(p_cidade), v_evento.nome, trim(p_tipo),
        trim(coalesce(p_observacao, '')), v_status, p_consentimento_lgpd
    ) returning inscritos.id, inscritos.ticket_code into v_id, v_ticket;

    if v_status = 'confirmado' then
        update public.eventos
           set vagas_ocupadas = least(vagas_total, vagas_ocupadas + 1)
         where eventos.id = p_evento_id;
    end if;

    insert into public.email_queue(recipient, template, payload)
    values (
        lower(trim(p_email)),
        'inscricao_confirmada',
        jsonb_build_object(
            'nome', trim(p_nome),
            'evento', v_evento.nome,
            'data_evento', v_evento.data_evento,
            'status', v_status,
            'ticket_code', v_ticket
        )
    );

    return query select v_id, v_ticket, v_status;
end;
$$;
revoke all on function public.criar_inscricao(bigint,text,text,text,text,text,text,boolean) from public;
grant execute on function public.criar_inscricao(bigint,text,text,text,text,text,text,boolean) to anon, authenticated;

create or replace function public.cancelar_inscricao(p_inscricao_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_inscricao public.inscritos%rowtype;
begin
    select * into v_inscricao
    from public.inscritos
    where inscritos.id = p_inscricao_id
    for update;

    if not found then
        raise exception 'Inscrição não encontrada.';
    end if;

    if not private.is_admin()
       and (select auth.uid()) is distinct from v_inscricao.user_id then
        raise exception 'Você não tem permissão para cancelar esta inscrição.';
    end if;

    if v_inscricao.checked_in_at is not null then
        raise exception 'Não é possível cancelar após o check-in.';
    end if;

    if v_inscricao.status = 'cancelado' then
        return true;
    end if;

    update public.inscritos
       set status = 'cancelado', cancelled_at = now()
     where id = p_inscricao_id;

    if v_inscricao.status = 'confirmado' and v_inscricao.evento_id is not null then
        update public.eventos
           set vagas_ocupadas = greatest(0, vagas_ocupadas - 1)
         where id = v_inscricao.evento_id;
    end if;

    return true;
end;
$$;
revoke all on function public.cancelar_inscricao(bigint) from public;
grant execute on function public.cancelar_inscricao(bigint) to authenticated;

create or replace function public.realizar_checkin(p_ticket_code text)
returns table(inscricao_id bigint, nome text, evento text, checked_in_at timestamptz)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_row public.inscritos%rowtype;
begin
    if not private.is_admin() then
        raise exception 'Acesso administrativo necessário.';
    end if;

    select * into v_row
    from public.inscritos
    where lower(inscritos.ticket_code) = lower(trim(p_ticket_code))
    for update;

    if not found then
        raise exception 'Ingresso não encontrado.';
    end if;

    if v_row.status = 'cancelado' then
        raise exception 'Esta inscrição foi cancelada.';
    end if;

    if v_row.checked_in_at is null then
        update public.inscritos
           set checked_in_at = now(), status = 'confirmado'
         where id = v_row.id
         returning * into v_row;
    end if;

    return query select v_row.id, v_row.nome, v_row.evento, v_row.checked_in_at;
end;
$$;
revoke all on function public.realizar_checkin(text) from public;
grant execute on function public.realizar_checkin(text) to authenticated;

create or replace function public.gerar_certificado(p_inscricao_id bigint)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_inscricao public.inscritos%rowtype;
    v_evento public.eventos%rowtype;
    v_codigo uuid;
begin
    select * into v_inscricao from public.inscritos where id = p_inscricao_id;
    if not found then raise exception 'Inscrição não encontrada.'; end if;

    if not private.is_admin()
       and (select auth.uid()) is distinct from v_inscricao.user_id then
        raise exception 'Sem permissão para gerar este certificado.';
    end if;

    if v_inscricao.checked_in_at is null then
        raise exception 'O certificado exige check-in confirmado.';
    end if;

    select * into v_evento from public.eventos where id = v_inscricao.evento_id;
    if not coalesce(v_evento.certificado_disponivel, false) then
        raise exception 'O certificado ainda não está disponível.';
    end if;

    insert into public.certificados(inscricao_id)
    values (p_inscricao_id)
    on conflict (inscricao_id) do update set inscricao_id = excluded.inscricao_id
    returning codigo into v_codigo;

    return v_codigo;
end;
$$;
revoke all on function public.gerar_certificado(bigint) from public;
grant execute on function public.gerar_certificado(bigint) to authenticated;

create or replace function public.validar_certificado(p_codigo uuid)
returns table(
    participante text,
    evento text,
    data_evento date,
    carga_horaria numeric,
    emitted_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select i.nome, e.nome, e.data_evento, e.carga_horaria, c.emitted_at
      from public.certificados c
      join public.inscritos i on i.id = c.inscricao_id
      join public.eventos e on e.id = i.evento_id
     where c.codigo = p_codigo
       and i.checked_in_at is not null
     limit 1;
$$;
revoke all on function public.validar_certificado(uuid) from public;
grant execute on function public.validar_certificado(uuid) to anon, authenticated;

-- ----------------------------------------------------------------
-- Row Level Security
-- ----------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.eventos enable row level security;
alter table public.inscritos enable row level security;
alter table public.contatos enable row level security;
alter table public.certificados enable row level security;
alter table public.email_queue enable row level security;
alter table public.audit_logs enable row level security;

-- Remove políticas antigas para evitar que regras acadêmicas permissivas continuem ativas.
do $$
declare
    p record;
begin
    for p in
        select schemaname, tablename, policyname
        from pg_policies
        where schemaname = 'public'
          and tablename in ('profiles','eventos','inscritos','contatos','certificados','email_queue','audit_logs')
    loop
        execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
    end loop;
end $$;

-- Nomes conhecidos das políticas acadêmicas antigas (mantidos como salvaguarda idempotente).
drop policy if exists "Permitir leitura publica" on public.inscritos;
drop policy if exists "Permitir cadastro publico" on public.inscritos;
drop policy if exists "Permitir leitura pública" on public.inscritos;
drop policy if exists "Permitir cadastro público" on public.inscritos;

-- Profiles
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select to authenticated
using ((select auth.uid()) = id or private.is_admin());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated
using ((select auth.uid()) = id or private.is_admin())
with check ((select auth.uid()) = id or private.is_admin());

-- Eventos
drop policy if exists eventos_public_read on public.eventos;
create policy eventos_public_read on public.eventos for select to anon, authenticated
using (status = 'publicado' and deleted_at is null);

drop policy if exists eventos_admin_read on public.eventos;
create policy eventos_admin_read on public.eventos for select to authenticated
using (private.is_admin());

drop policy if exists eventos_admin_insert on public.eventos;
create policy eventos_admin_insert on public.eventos for insert to authenticated
with check (private.is_admin());

drop policy if exists eventos_admin_update on public.eventos;
create policy eventos_admin_update on public.eventos for update to authenticated
using (private.is_admin()) with check (private.is_admin());

drop policy if exists eventos_admin_delete on public.eventos;
create policy eventos_admin_delete on public.eventos for delete to authenticated
using (private.is_admin());

-- Inscrições: leitura própria ou administrativa. Criação apenas pela RPC.
drop policy if exists inscritos_select_own on public.inscritos;
create policy inscritos_select_own on public.inscritos for select to authenticated
using ((select auth.uid()) = user_id or private.is_admin());

drop policy if exists inscritos_admin_update on public.inscritos;
create policy inscritos_admin_update on public.inscritos for update to authenticated
using (private.is_admin()) with check (private.is_admin());

drop policy if exists inscritos_admin_delete on public.inscritos;
create policy inscritos_admin_delete on public.inscritos for delete to authenticated
using (private.is_admin());

-- Contatos
drop policy if exists contatos_public_insert on public.contatos;
create policy contatos_public_insert on public.contatos for insert to anon, authenticated
with check (user_id is null or user_id = (select auth.uid()));

drop policy if exists contatos_select on public.contatos;
create policy contatos_select on public.contatos for select to authenticated
using (private.is_admin() or user_id = (select auth.uid()));

drop policy if exists contatos_admin_update on public.contatos;
create policy contatos_admin_update on public.contatos for update to authenticated
using (private.is_admin()) with check (private.is_admin());

drop policy if exists contatos_admin_delete on public.contatos;
create policy contatos_admin_delete on public.contatos for delete to authenticated
using (private.is_admin());

-- Certificados
drop policy if exists certificados_select_own on public.certificados;
create policy certificados_select_own on public.certificados for select to authenticated
using (
    private.is_admin()
    or exists (
        select 1 from public.inscritos i
        where i.id = certificados.inscricao_id
          and i.user_id = (select auth.uid())
    )
);

-- Filas e auditoria apenas administrativas
drop policy if exists email_queue_admin_all on public.email_queue;
create policy email_queue_admin_all on public.email_queue for all to authenticated
using (private.is_admin()) with check (private.is_admin());

drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs for select to authenticated
using (private.is_admin());

-- Privilégios de Data API. A RLS continua sendo a barreira de acesso por linha.
revoke all on public.profiles, public.eventos, public.inscritos, public.contatos,
    public.certificados, public.email_queue, public.audit_logs from anon, authenticated;

grant select on public.eventos to anon;
grant select, insert, update, delete on public.eventos to authenticated;
grant select, update on public.profiles to authenticated;
grant select, update, delete on public.inscritos to authenticated;
grant insert on public.contatos to anon;
grant select, insert, update, delete on public.contatos to authenticated;
grant select on public.certificados to authenticated;
grant select, insert, update, delete on public.email_queue to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ----------------------------------------------------------------
-- Depois de criar sua conta pelo site, promova o primeiro administrador:
-- update public.profiles set role = 'admin' where email = 'SEU_EMAIL@EXEMPLO.COM';
-- ----------------------------------------------------------------
